# Generated by Django 4.1 on 2022-08-29 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Socio',
            new_name='Socios',
        ),
    ]
