# Generated by Django 4.1 on 2022-08-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega', '0002_rename_socio_socios'),
    ]

    operations = [
        migrations.AddField(
            model_name='deportes',
            name='comision',
            field=models.CharField(default=1000, max_length=50),
            preserve_default=False,
        ),
    ]
