# Generated by Django 4.1 on 2022-08-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega', '0003_deportes_comision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deportes',
            name='comision',
            field=models.IntegerField(max_length=50),
        ),
    ]
